# Default settings for Pascal on Windows
compilerType=pascal-win
supportsBinary=true
rpathFlag=-O
objdumper=objdump
demangler=
versionFlag=| grep "Version"

# Compilers are defined in pascal-win.local.properties
