# Windows Local Deployment - Python
# Local Python installation - version 3.13.9

compilers=pythonlocal
defaultCompiler=pythonlocal

compiler.pythonlocal.exe=C:\Users\User\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe
compiler.pythonlocal.name=Python 3.13.9 (local)
compiler.pythonlocal.semver=3.13.9

supportsBinary=false
interpreted=true
compilerType=python
objdumper=
instructionSet=python
