# Windows Local Deployment - Python
# Local Python installation - version 3.13.9

compilers=pythonlocal
defaultCompiler=pythonlocal

compiler.pythonlocal.exe=python
compiler.pythonlocal.name=Python 3.13.9 (local)
compiler.pythonlocal.semver=3.13.9

supportsBinary=false
interpreted=true
compilerType=python
objdumper=
instructionSet=python
